setup1:
  ref_genome: sfu_hivs/OR483991.1.fasta
  input_folder: sfu_hivs
  genomes:
    - OR483999
    - OR483988
    - OR483990
    - OR483987
    - OR484006
    - OR484012
    - OR483993
  ratio:
    - 20
    - 10
    - 9
    - 7
    - 5
    - 3
    - 1
  coverages:
    - 3
    - 5
    - 7
    - 10
    - 15
    - 20
    - 30
    - 40
    - 50
    - 60
    - 80
    - 120
    - 160
  lengths:
    - 3000
    - 9000
  read_identities:
    - 98
    - 95
